#!/bin/bash

source /usr/local/cloud/network_service

declare -A arg_dict
arg_count=0

usage() {
    echo "Usage: ./allow_vlan_trunks -v <vlan> -d <share> -l <logfile>"
} 

while getopts "v:d:l:" opt; 
do
    case $opt in
        v)
            vlan=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        d)
            arg_dict["share"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        l)
            arg_dict["logfile"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
    esac
done

if [ $arg_count != 3 ]
    then
        usage
        exit -1
fi

touch "${arg_dict["share"]}/logs/status.txt"
logfilepath="${arg_dict["share"]}/logs/${arg_dict["logfile"]}"
allow_bridge_vlan_trunks ovs-br1 $vlan $logfilepath
allow_bridge_vlan_trunks tap_soft $vlan $logfilepath

status=$?
if [ "$status" == 0 ]; then
    out_dict["status"]="SUCCESS"
    out_dict["data"]="allow vlan trunk is success"
    echo -e "{\"status\":\""${out_dict["status"]}"\", \"data\":\""${out_dict["data"]}"\"}" >> "${arg_dict["share"]}/logs/${arg_dict["logfile"]}"
    echo -e "{\"status\":\""${out_dict["status"]}"\", \"data\":\""${out_dict["data"]}"\"}" > "${arg_dict["share"]}/logs/status.txt"
fi    

