#!/bin/bash

source /usr/local/cloud/network_service

declare -A arg_dict
arg_count=0

usage() {
    echo "Usage: ./restart_dhcp_relay -g <ip> -s <subnet> -n <netmask> \
    -i <container_image> -v <vlan> -d <share> -c <cust_id> -a <range_start> \
    -z <range_end> -l <logfile>"
} 


while getopts "s:i:v:d:l:n:c:a:z:g:" opt; 
do
    case $opt in
        s)
            arg_dict["subnet"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        i)
            arg_dict["container_name"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        v)
            arg_dict["vlan"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        d)
            arg_dict["share"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        l)
            arg_dict["logfile"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
		n)
            arg_dict["netmask"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        c)
            arg_dict["cust_id"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        a)
            arg_dict["range_start"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        z)
            arg_dict["range_end"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        g)
            arg_dict["ip"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
    esac
done

if [ $arg_count != 10 ]
    then
        usage
        exit -1
fi

touch "${arg_dict["share"]}/logs/status.txt"
restart_dhcp_relay arg_dict
  
status=$?
if [ "$status" == 0 ]; then
    out_dict["status"]="SUCCESS"
    out_dict["data"]="DHCP relay setup is success"
    echo -e "{\"status\":\""${out_dict["status"]}"\", \"data\":\""${out_dict["data"]}"\"}" >> "${arg_dict["share"]}/logs/${arg_dict["logfile"]}"
    echo -e "{\"status\":\""${out_dict["status"]}"\", \"data\":\""${out_dict["data"]}"\"}" > "${arg_dict["share"]}/logs/status.txt"
fi    
