#!/bin/bash

source /usr/local/cloud/network_service

usage() {
    echo "Usage: ./start_dhcp_server -g <public_ip> -s <subnet> -n <netmask> -i <container_image> \
                    -d <share> -l <logfile> -a <range_start> -z <range_end>"
} 

declare -A arg_dict
arg_count=0
while getopts "s:i:d:l:n:a:z:" opt; 
do
    case $opt in
        s)
            arg_dict["subnet"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        i)
            arg_dict["container_image"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        a)
            arg_dict["range_start"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        z)
            arg_dict["range_end"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        d)
            arg_dict["share"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
        l)
            arg_dict["logfile"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
		n)
            arg_dict["netmask"]=$OPTARG
            arg_count=$(($arg_count+1))
            ;;
    esac
done

touch "${arg_dict["share"]}/logs/status.txt"

if [ $arg_count != 7 ]
    then
        usage
        exit -1
fi
start_dhcp_server arg_dict
  
status=$?
if [ "$status" == 0 ]; then
    out_dict["status"]="SUCCESS"
    out_dict["data"]="DHCP server setup is success"
    echo -e "{\"status\":\""${out_dict["status"]}"\", \"data\":\""${out_dict["data"]}"\"}" >> "${arg_dict["share"]}/logs/${arg_dict["logfile"]}"
    echo -e "{\"status\":\""${out_dict["status"]}"\", \"data\":\""${out_dict["data"]}"\"}" > "${arg_dict["share"]}/logs/status.txt"
fi    
